#!/usr/bin/env bash
# Rerunnable deploy of the EventBuddy Custom Agent to GreenNode AgentBase.
#
# Pipeline: preflight -> CR login -> docker build -> docker push ->
#           create-or-update runtime (--from-cr) -> poll ACTIVE ->
#           resolve DEFAULT endpoint -> health check.
#
# Idempotent: if a runtime named "$RUNTIME_NAME" already exists it is UPDATED
# (new version), otherwise it is CREATED. Safe to run repeatedly.
#
# Config via env vars (all have sane Phase-1 defaults):
#   RUNTIME_NAME   runtime + image name           (default: eventbuddy-phase1)
#   FLAVOR         compute flavor                  (default: runtime-s2-general-2x4)
#   ENV_FILE       env file injected at runtime    (default: .env; "none" to skip)
#   PLATFORM       docker build platform           (default: linux/amd64)
#   TAG            image tag                        (default: vYYYYMMDDHHMMSS)
#   MIN_REPLICAS / MAX_REPLICAS / CPU_SCALE / MEM_SCALE  autoscaling
#
# Secrets never touch this script: IAM creds live in .greennode.json (run
# `make creds`), the CR push secret is piped in-memory by cr.sh.
set -euo pipefail

# --- ensure jq (installed to ~/.local/bin) is reachable ---
export PATH="$HOME/.local/bin:$PATH"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
SCRIPTS=".claude/skills/agentbase/scripts"

RUNTIME_NAME="${RUNTIME_NAME:-eventbuddy-phase1}"
FLAVOR="${FLAVOR:-runtime-s2-general-2x4}"
ENV_FILE="${ENV_FILE:-.env}"
PLATFORM="${PLATFORM:-linux/amd64}"
MIN_REPLICAS="${MIN_REPLICAS:-1}"
MAX_REPLICAS="${MAX_REPLICAS:-1}"
CPU_SCALE="${CPU_SCALE:-50}"
MEM_SCALE="${MEM_SCALE:-50}"

# Timestamp tag — Date.now()-style; generated by the shell, not baked in.
TAG="${TAG:-v$(date +%Y%m%d%H%M%S)}"

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- preflight
say "Preflight checks"
command -v jq    >/dev/null || die "jq not found on PATH (expected ~/.local/bin/jq)."
command -v docker >/dev/null || die "docker not found."
[ -f deployment/Dockerfile ] || die "deployment/Dockerfile missing in $ROOT."
[ -d "$SCRIPTS" ] || die "AgentBase skill scripts not found at $SCRIPTS (install them first)."

if ! bash "$SCRIPTS/check_credentials.sh" iam >/dev/null 2>&1; then
  die "IAM credentials missing. Run 'make creds' to store your client_id + secret first."
fi
ok "jq, docker, Dockerfile, IAM credentials present"

ENV_ARG=()
if [ "$ENV_FILE" != "none" ] && [ -n "$ENV_FILE" ]; then
  [ -f "$ENV_FILE" ] || die "ENV_FILE '$ENV_FILE' not found (set ENV_FILE=none to deploy without one)."
  ENV_ARG=(--env-file "$ENV_FILE")
  ok "Will inject env file: $ENV_FILE  (ensure it has NO GREENNODE_* vars — those are auto-injected)"
else
  ok "No env file (ENV_FILE=none)"
fi

# ------------------------------------------------------------ registry info
say "Reading AgentBase Container Registry info"
REPO_JSON="$(bash "$SCRIPTS/cr.sh" repo get)" || die "cr.sh repo get failed (token/permissions?)."
REGISTRY_URL="$(echo "$REPO_JSON" | jq -r '.registryUrl // empty')"
REPO_NAME="$(echo "$REPO_JSON"  | jq -r '.name // empty')"
[ -n "$REGISTRY_URL" ] && [ -n "$REPO_NAME" ] || die "Could not read registryUrl/name from CR repo response."
IMAGE="${REGISTRY_URL}/${REPO_NAME}/${RUNTIME_NAME}:${TAG}"
ok "Registry: $REGISTRY_URL  repo: $REPO_NAME"
ok "Image:    $IMAGE"

say "Logging in to the Container Registry (secret piped in-memory)"
bash "$SCRIPTS/cr.sh" credentials docker-login || die "CR docker-login failed."
ok "Docker logged in to $REGISTRY_URL"

# -------------------------------------------------------------- build/push
say "Building image for $PLATFORM"
docker build --platform "$PLATFORM" -f deployment/Dockerfile -t "$IMAGE" . || die "docker build failed."
ok "Built $IMAGE"

say "Pushing image"
docker push "$IMAGE" || die "docker push failed (check CR login / quota)."
ok "Pushed $IMAGE"

# --------------------------------------------------- create or update runtime
say "Looking up existing runtime named '$RUNTIME_NAME'"
LIST_JSON="$(bash "$SCRIPTS/runtime.sh" list --size 100)" || die "runtime.sh list failed."
RUNTIME_ID="$(echo "$LIST_JSON" | jq -r --arg n "$RUNTIME_NAME" '.listData[]? | select(.name==$n) | .id' | head -1)"

if [ -n "$RUNTIME_ID" ] && [ "$RUNTIME_ID" != "null" ]; then
  say "Updating existing runtime $RUNTIME_ID (new version)"
  RESP="$(bash "$SCRIPTS/runtime.sh" update "$RUNTIME_ID" \
    --image "$IMAGE" --flavor "$FLAVOR" "${ENV_ARG[@]}" \
    --min-replicas "$MIN_REPLICAS" --max-replicas "$MAX_REPLICAS" \
    --cpu-scale "$CPU_SCALE" --mem-scale "$MEM_SCALE" \
    --from-cr)" || die "runtime update failed."
else
  say "Creating new runtime '$RUNTIME_NAME'"
  RESP="$(bash "$SCRIPTS/runtime.sh" create \
    --name "$RUNTIME_NAME" --image "$IMAGE" --flavor "$FLAVOR" "${ENV_ARG[@]}" \
    --min-replicas "$MIN_REPLICAS" --max-replicas "$MAX_REPLICAS" \
    --cpu-scale "$CPU_SCALE" --mem-scale "$MEM_SCALE" \
    --from-cr)" || die "runtime create failed."
  RUNTIME_ID="$(echo "$RESP" | jq -r '.id // empty')"
fi
[ -n "$RUNTIME_ID" ] && [ "$RUNTIME_ID" != "null" ] || die "Could not determine runtime id from response: $RESP"
ok "Runtime id: $RUNTIME_ID"

# ---------------------------------------------------------- poll for ACTIVE
say "Waiting for runtime to reach ACTIVE (polling every 10s, ~10m timeout)"
DEADLINE=$(( $(date +%s) + 600 ))
STATUS=""
while [ "$(date +%s)" -lt "$DEADLINE" ]; do
  STATUS="$(bash "$SCRIPTS/runtime.sh" get "$RUNTIME_ID" | jq -r '.status // "UNKNOWN"')"
  printf '   status: %s\n' "$STATUS"
  case "$STATUS" in
    ACTIVE) break ;;
    ERROR)  die "Runtime entered ERROR state. Inspect logs: make logs" ;;
  esac
  sleep 10
done
[ "$STATUS" = "ACTIVE" ] || die "Runtime did not reach ACTIVE in time (last status: $STATUS)."
ok "Runtime is ACTIVE"

# --------------------------------------------------- resolve DEFAULT endpoint
say "Resolving DEFAULT endpoint URL"
EP_JSON="$(bash "$SCRIPTS/runtime.sh" endpoints list "$RUNTIME_ID")" || die "endpoints list failed."
URL="$(echo "$EP_JSON" | jq -r '.listData[]? | select((.name // "")|ascii_downcase=="default") | .url' | head -1)"
[ -n "$URL" ] && [ "$URL" != "null" ] || URL="$(echo "$EP_JSON" | jq -r '.listData[0]?.url // empty')"
[ -n "$URL" ] || die "Could not find an endpoint URL."
ok "Endpoint: $URL"

# --------------------------------------------------------------- health check
say "Health check ${URL%/}/health"
CODE=""
for _ in $(seq 1 12); do
  CODE="$(curl -s -o /dev/null -w '%{http_code}' "${URL%/}/health" || true)"
  [ "$CODE" = "200" ] && break
  printf '   waiting for health (got %s)...\n' "${CODE:-no-response}"
  sleep 5
done

echo
echo "────────────────────────────────────────────"
echo " Deployment complete — EventBuddy Phase 1 (Lifecycle Core)"
echo "   Runtime:    $RUNTIME_NAME"
echo "   Runtime ID: $RUNTIME_ID"
echo "   Image:      $IMAGE"
echo "   Status:     $STATUS"
echo "   Endpoint:   $URL"
if [ "$CODE" = "200" ]; then
  echo "   Health:     OK (200)"
else
  echo "   Health:     NOT READY (last code: ${CODE:-none}) — container may still be warming; retry: curl ${URL%/}/health"
fi
echo "   Console:    https://aiplatform.console.vngcloud.vn/agent-runtime?tab=runtime"
echo "────────────────────────────────────────────"
echo
echo "Phase 1 serves: GET /health · POST /api/messages (Bot Framework) ·"
echo "POST /api/webhooks/graph · POST /api/dev/handle (if DEV_ROUTES_ENABLED=true)."
echo "Wire this endpoint into the Azure Bot messaging endpoint: ${URL%/}/api/messages"
[ "$CODE" = "200" ] || exit 1
